# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 13:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0008_auto_20151210_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTrackLevelRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('feedback', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('comment', models.TextField(max_length=8192)),
                ('event_track_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventTrackLevel')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleItemRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('feedback', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('comment', models.TextField(max_length=8192)),
                ('schedule_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.ScheduleItem')),
            ],
        ),
    ]
