# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
