# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20160110_1629'),
        ('feed', '0002_auto_20160103_2105'),
    ]

    operations = [
    ]
