# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 21:41
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20151021_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('from_datetime', models.DateTimeField()),
                ('to_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('P', 'Party')], default='P', max_length=1)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('event_track_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='events.EventTrackLevel')),
            ],
        ),
        migrations.AddField(
            model_name='openinghours',
            name='schedule_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='events.ScheduleItem'),
        ),
    ]
