# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20151210_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='type',
            field=models.CharField(choices=[('P', 'Party'), ('M', 'Main class'), ('T', 'Taster class'), ('A', 'Other activity')], default='P', max_length=1),
        ),
    ]
